cluster.name: "es-docker-cluster"
network.host: 0.0.0.0

# Enable ingest pipelines
ingest.geoip.downloader.enabled: false

# Disable security features for development
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Enable monitoring
xpack.monitoring.collection.enabled: true

# Increase timeout for large document processing
http.max_content_length: 500mb
