global:
  resolve_timeout: 5m
  slack_api_url: 'http://slack-webhook-url'  # To be configured

route:
  group_by: ['alertname', 'doc_type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#court-data-alerts'
    send_resolved: true
    title: '{{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Document Type:* {{ .Labels.doc_type }}
        *Severity:* {{ .Labels.severity }}
        *Value:* {{ .Annotations.value }}
      {{ end }}
