global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'court-data-pipeline'
    static_configs:
      - targets: ['localhost:8000']  # Metrics endpoint for our pipeline
    metrics_path: '/metrics'

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['localhost:9200']
    metrics_path: '/_prometheus/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9308']  # JMX Exporter for Kafka
